# Generated by Django 4.1.4 on 2023-08-02 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_duration', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.college')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('student_number', models.CharField(max_length=50, unique=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.college')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.department')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.school')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_year_of_study', models.PositiveIntegerField()),
                ('current_semester', models.CharField(max_length=10)),
                ('course_unit_name', models.CharField(max_length=100)),
                ('course_code', models.CharField(max_length=20)),
                ('facility_name', models.CharField(max_length=100)),
                ('facility_rating', models.PositiveIntegerField()),
                ('facility_comments', models.TextField()),
                ('lecturer_name', models.CharField(max_length=100)),
                ('lecturer_rating', models.PositiveIntegerField()),
                ('lecturer_comments', models.TextField()),
                ('suggestions', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.student')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.school'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.department'),
        ),
    ]
